name: ğŸ—ï¸ Build
on: [push]

jobs:
  lint:
    name: ğŸ‘– ESLint
    runs-on: ubuntu-latest
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      # Need to build CSS before linting because root.tsx references the generated Tailwind
      # stylesheet.
      - name: ğŸ—ï¸ Build CSS
        run: npm run build:css

      - name: ğŸ‘– Lint
        run: npm run lint

  types:
    name: ğŸ” TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ” Type check
        run: npm run types

  vitest:
    name: âš¡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: âš¡ Run vitest
        run: npm run test

  codegen:
    name: âŒ¨ï¸ Codegen
    runs-on: ubuntu-latest
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: âŒ¨ï¸ Validate no pending codegen
        run: npm run codegen -- --check

  storybook:
    name: ğŸ“š Storybook
    runs-on: ubuntu-latest
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“š Build storybook
        run: npm run storybook:build

      - name: ğŸ¤Ÿ Accessibility tests
        run: npm run test:storybook:axeOnly

      # # To use Chromatic for [visual regression testing](https://czi.atlassian.net/wiki/x/SYCFiw):
      # # 1. Un-comment this entire block.
      # # 2. Create a new project in Chromatic per https://www.chromatic.com/docs/setup#sign-up.
      # # 3. Add its unique project token to GitHub as a `CHROMATIC_PROJECT_TOKEN` secret.
      # - name: ğŸŒˆ Publish to Chromatic
      #   uses: chromaui/action@v1
      #   with:
      #     autoAcceptChanges: main
      #     exitOnceUploaded: true
      #     onlyChanged: true
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     storybookBuildDir: storybook-static
