name: ğŸ—ï¸ Build
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ğŸ‘– ESLint
    runs-on: ubuntu-latest
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      # Need to build CSS before linting because root.tsx references the generated Tailwind
      # stylesheet.
      - name: ğŸ—ï¸ Build CSS
        run: npm run build:css

      - name: ğŸ‘– Lint
        run: npm run lint

  types:
    name: ğŸ” TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ” Type check
        run: npm run types

  vitest:
    name: âš¡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: âš¡ Run vitest
        run: npm run test -- --coverage

  playwright:
    name: ğŸ¤© Playwright
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5433/test
      SESSION_SECRET: 1347abaec6b43d718213d78d60c932f9
    steps:
      - name: â›” Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ˜» Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: ğŸ³ Docker compose
        # the sleep is just there to give time for postgres to get started
        run: docker-compose up -d && sleep 3

      - name: ğŸ›  Setup Database
        run: npx prisma migrate reset --force

      - name: ğŸ—ï¸ Build
        run: npm run build

      - name: ğŸ¤© Playwright run
        # Note that this doesn't use `npm run test:e2e`. Getting the env vars setup right in the
        # dev vs test environments has been... challenging. For now the workaround is to use the
        # package.json script for local test runs only, and manually setting up the env vars.
        run: npx playwright test
